---
title: "Transcript Annotation Database for *Glycine max*"
author: "Kabilan S"
date: "2026-08-15"
output: BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{Transcript Annotation Database for Glycine max}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

**TxDb.Gmax.JGI.Gmv4** is a Bioconductor-compatible transcript annotation
package for *Glycine max* generated from the official **JGI/Phytozome GFF3
annotation** GFF3 annotation based on the **Glycine max Wm82.a4.v1** reference
genome.

The package provides genomic coordinates and transcript models, including genes,
transcripts, exons, coding sequences (CDS), and promoter regions. It is intended
for downstream genomic analyses using Bioconductor packages such as
**GenomicFeatures**, **GenomicRanges**, **Signac**, **ArchR**, and
**ChIPseeker**.

The TxDb object itself is not shipped inside the package; it is hosted on
**AnnotationHub** and downloaded on first use.


``` r
# Installation
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
BiocManager::install(c(
    "AnnotationHub",
    "GenomicFeatures",
    "GenomicRanges"
))
```

# Loading the package


``` r
library(TxDb.Gmax.JGI.Gmv4)
```

```
## Error in `library()`:
## ! there is no package called 'TxDb.Gmax.JGI.Gmv4'
```

``` r
library(GenomicFeatures)
library(GenomicRanges)
```


``` r
# Downloading the TxDb file from AnnotationHub
TxDb.Gmax.JGI.Gmv4 <- tryCatch({
    ah <- AnnotationHub()
    ah[["AH122288"]]
}, error = function(e) NULL)
```



# Package summary


``` r
TxDb.Gmax.JGI.Gmv4
```

# Chromosome information


``` r
seqinfo(TxDb.Gmax.JGI.Gmv4)
```

# Available chromosomes


``` r
seqlevels(TxDb.Gmax.JGI.Gmv4)
```
The 20 nuclear chromosomes of the Glycine max Wm82.a4.v1 assembly. These contain
the vast majority of annotated genes.

# Gene annotations

Retrieve all annotated genes.


``` r
genes(TxDb.Gmax.JGI.Gmv4)
```

# Transcript annotations


``` r
head(transcripts(TxDb.Gmax.JGI.Gmv4))
```

# Exon annotations


``` r
head(exons(TxDb.Gmax.JGI.Gmv4))
```

# Coding sequence (CDS) annotations


``` r
head(cds(TxDb.Gmax.JGI.Gmv4))
```

# Promoter regions

Extract promoter regions 2 kb upstream and 200 bp downstream of transcription
start sites.


``` r
head(promoters(
    TxDb.Gmax.JGI.Gmv4,
    upstream = 2000,
    downstream = 200
))
```

# Transcripts grouped by gene


``` r
tx_by_gene <- GenomicFeatures::transcriptsBy(TxDb.Gmax.JGI.Gmv4, by = "gene")
tx_by_gene
```

# Exons grouped by transcript


``` r
exonsBy(TxDb.Gmax.JGI.Gmv4, by = "tx")
```

# Session information


``` r
sessionInfo()
```

```
## R version 4.6.1 (2026-06-24 ucrt)
## Platform: x86_64-w64-mingw32/x64
## Running under: Windows 11 x64 (build 26200)
## 
## Matrix products: default
##   LAPACK version 3.12.1
## 
## locale:
## [1] LC_COLLATE=English_India.utf8  LC_CTYPE=English_India.utf8   
## [3] LC_MONETARY=English_India.utf8 LC_NUMERIC=C                  
## [5] LC_TIME=English_India.utf8    
## 
## time zone: Asia/Calcutta
## tzcode source: internal
## 
## attached base packages:
## [1] stats4    stats     graphics  grDevices utils     datasets 
## [7] methods   base     
## 
## other attached packages:
##  [1] GenomicFeatures_1.65.0 AnnotationDbi_1.74.0  
##  [3] Biobase_2.73.2         GenomicRanges_1.64.0  
##  [5] Seqinfo_1.2.0          IRanges_2.46.0        
##  [7] S4Vectors_0.50.1       BiocGenerics_0.58.1   
##  [9] generics_0.1.4         knitr_1.51            
## 
## loaded via a namespace (and not attached):
##  [1] SparseArray_1.13.2          bitops_1.1-0               
##  [3] lattice_0.22-9              RSQLite_3.53.3             
##  [5] digest_0.6.39               grid_4.6.1                 
##  [7] evaluate_1.0.5              fastmap_1.2.0              
##  [9] blob_1.3.0                  Matrix_1.7-6               
## [11] cigarillo_1.3.1             restfulr_0.0.17            
## [13] DBI_1.3.0                   httr_1.4.8                 
## [15] XML_3.99-0.23               Biostrings_2.80.1          
## [17] codetools_0.2-20            abind_1.4-8                
## [19] cli_3.6.6                   rlang_1.3.0                
## [21] crayon_1.5.3                XVector_0.52.0             
## [23] bit64_4.8.2                 DelayedArray_0.38.2        
## [25] cachem_1.1.0                yaml_2.3.12                
## [27] otel_0.2.0                  S4Arrays_1.13.0            
## [29] tools_4.6.1                 parallel_4.6.1             
## [31] BiocParallel_1.47.0         memoise_2.0.1              
## [33] Rsamtools_2.29.0            SummarizedExperiment_1.42.0
## [35] curl_7.1.0                  vctrs_0.7.3                
## [37] R6_2.6.1                    png_0.1-9                  
## [39] matrixStats_1.5.0           BiocIO_1.22.0              
## [41] lifecycle_1.0.5             rtracklayer_1.73.0         
## [43] KEGGREST_1.53.6             bit_4.6.0                  
## [45] pillar_1.11.1               rsconnect_1.10.1           
## [47] glue_1.8.1                  xfun_0.60                  
## [49] GenomicAlignments_1.49.1    MatrixGenerics_1.24.0      
## [51] rstudioapi_0.19.0           rjson_0.2.23               
## [53] htmltools_0.5.9             rmarkdown_2.31             
## [55] compiler_4.6.1              RCurl_1.98-1.19
```
